[alias]
"@/" = "./apps/www.k3h4.io/src/"
"@/components/" = "./apps/www.k3h4.io/src/components/"
"@/radix-components/" = "./apps/www.k3h4.io/src/radix-components/"
"@/radix-primitives/" = "./apps/www.k3h4.io/src/radix-primitives/"
"@/r3f-components/" = "./apps/www.k3h4.io/src/r3f-components/"
"@/r3f-primitives/" = "./apps/www.k3h4.io/src/r3f-primitives/"
"@/react-hooks/" = "./apps/www.k3h4.io/src/react-hooks/"
"@/zustand-stores/" = "./apps/www.k3h4.io/src/zustand-stores/"
"@/pages/" = "./apps/www.k3h4.io/src/pages/"
"@/lib/" = "./apps/www.k3h4.io/src/lib/"
