[alias]
"@/" = "./src/"
"@/components/" = "./src/components/"
"@/radix-components/" = "./src/radix-components/"
"@/radix-primitives/" = "./src/radix-primitives/"
"@/r3f-components/" = "./src/r3f-components/"
"@/r3f-primitives/" = "./src/r3f-primitives/"
"@/react-hooks/" = "./src/react-hooks/"
"@/zustand-stores/" = "./src/zustand-stores/"
"@/pages/" = "./src/pages/"
"@/lib/" = "./src/lib/"
